language: en-US
tone_instructions: "Use a friendly and encouraging tone while being concise and direct in feedback. In your review summary, take on the role of an editor (rather than a proof-reader) and give principle-based guidance on overall software design."
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  path_filters: []
  path_instructions:
    - path: "**/*.tf"
      instructions: |
        Review the Terraform code using these rules:
          - use comment blocks for comments
          -  2 empty lines before a comment block
          -  1 empty line before a code block
          - foreach always has an empty set as an option in case the module is not enabled
          - code must obey the SevenPico Style Guide and the SevenPico Code Review Checklist:
            - SevenPico Style Guide is available at local path `./.standards/sevenpico-style-guide.yaml`
            - SevenPico Code Review Checklist is available at local path `./.standards/sevenpico-code-review-checklist.yaml`
    - path: "**/*.hcl"
      instructions: |
        Review the Terragrunt code using these rules:
          - use comment blocks for comments
          -  2 empty lines before a comment block
          -  1 empty line before a code block
          - foreach always has an empty set as an option in case the module is not enabled
          - code must obey the SevenPico Style Guide and the SevenPico Code Review Checklist:
            - SevenPico Style Guide is available at local path `./.standards/sevenpico-style-guide.yaml`
            - SevenPico Code Review Checklist is available at local path `./.standards/sevenpico-code-review-checklist.yaml`
  abort_on_close: true
  auto_review:
    enabled: true
    drafts: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    base_branches:
      - develop
      - feature/*
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    ast-grep:
      packages: []
      rule_dirs: []
      util_dirs: []
      essential_rules: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys:
      - SPI
  linear:
    team_keys: []
